[tool.poetry]
name = "accord_api"
version = "0.1.0"
description = ""
authors = ['nata-keberle']

[tool.poetry.dependencies]
python = "3.10.*"
uvicorn = "^0.20.0"
requests = "^2.28.2"
fastapi = "^0.103"
httpx = "^0.27.0"
python-dotenv = "^1.0.1"
 

