name: publish
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - run: "bunx @redocly/cli build-docs BuildingCodesAndRules/BuildingCodesAndRules.yaml"
      - run: mkdir dist
      - run: mv redoc-static.html dist/buildingcodesandrules.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1