#!/bin/bash
REGISTRY_PATH="registry.git.cf.ac.uk/accord"
docker login $REGISTRY_PATH	
mvn package
docker build -t $REGISTRY_PATH/regulationsapi . --platform=linux/amd64 
docker push $REGISTRY_PATH/regulationsapi
rm -rf dist